### PR TITLE
Created Spanish strings.xml

### PR DESCRIPTION
**Pull request by ordago**
Spanish translation

### CODE REVIEW

**Comment by viks77** [comment]
ordago: Today I'm trying to build application for Android Market, but it needs one more Spanish string. New string "Vibration on wrong answers" needs to be translated. Can You help with that?

**Comment by ordago** [comment]
"Vibra cuando respondes incorrectamente" ("vibrates when you respond incorrectly")

"Vibra cuando se responde incorrectamente" (Impersonal: "vibrates when responded incorrectly")

It'd be better having the other strings to fit the style.

**Comment by viks77** [comment]
Unfortunately, because of lost signing key, I can't publish updates to my old application anymore.
Today i uploaded new one (Music Sight Reading II):
https://play.google.com/store/apps/details?id=com.viks.sire2

**Comment by ordago** [comment]
Thanks. Updated to the new one.

**Pull request merged**
